### PR TITLE
Create QuickSort.py

### PR DESCRIPTION
**Pull request by maneesh1510**
Adding a new file QuickSort.py to implement QuickSort algorithm in python.

### CODE REVIEW

**Comment by maneesh1510** [comment]
please drop a comment if you want to give me any suggestion about the code and algorithm.

**Comment by maneesh1510** [comment]
I will be so glad to have your advice

**Comment by d-s-2803** [comment]
Great Work!! No conflicts and pretty neat.. I'm merging this. Thanks for the contribution.

**Comment by maneesh1510** [comment]
thank you

**Pull request merged**
